// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationMVCCrudwithAjax.Data;

#nullable disable

namespace WebApplicationMVCCrudwithAjax.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationMVCCrudwithAjax.Models.Employee", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Code")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DobStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = "Yes",
                            City = "Mumbai",
                            Code = 101,
                            Dob = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DobStr = "12-05-1990",
                            Gender = "Female",
                            Image = "alice.jpg",
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Active = "Yes",
                            City = "Delhi",
                            Code = 102,
                            Dob = new DateTime(1985, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DobStr = "23-08-1985",
                            Gender = "Male",
                            Image = "bob.jpg",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Active = "No",
                            City = "Bangalore",
                            Code = 103,
                            Dob = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DobStr = "15-03-1992",
                            Gender = "Male",
                            Image = "charlie.jpg",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Active = "Yes",
                            City = "Chennai",
                            Code = 104,
                            Dob = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DobStr = "05-12-1995",
                            Gender = "Female",
                            Image = "diana.jpg",
                            Name = "Diana"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
